#=============================================================================
#RFC 4740 Diameter SIP Application

DIAMETER_COMMAND_UAR = 283 # User-Authorization-Request / Answer
DIAMETER_COMMAND_SAR = 284 # Server-Assignment-Request / Answer
DIAMETER_COMMAND_LIR = 285 # Location-Info-Request / Answer
DIAMETER_COMMAND_MAR = 286 # Multimedia-Auth-Request / Answer
DIAMETER_COMMAND_RTR = 287 # Registration-Termination-Request / Answer
DIAMETER_COMMAND_PPR = 288 # Push-Profile-Request  / Answer

#AVPs

DIA_SIP_ACCOUNTING_INFORMATION      = 368
DIA_SIP_ACCOUNTING_SERVER_URI       = 369
DIA_SIP_CREDIT_CONTROL_SERVER_URI   = 370
DIA_SIP_SERVER_URI                  = 371
DIA_SIP_SERVER_CAPABILITIES         = 372
DIA_SIP_MANDATORY_CAPABILITY        = 373
DIA_SIP_OPTIONAL_CAPABILITY         = 374
DIA_SIP_SERVER_ASSIGNMENT_TYPE      = 375
DIA_SIP_AUTH_DATA_ITEM              = 376
DIA_SIP_AUTHENTICATION_SCHEME       = 377
DIA_SIP_ITEM_NUMBER                 = 378
DIA_SIP_AUTHENTICATE                = 379
DIA_SIP_AUTHORIZATION               = 380
DIA_SIP_AUTHENTICATION_INFO         = 381
DIA_SIP_NUMBER_AUTH_ITEMS           = 382
DIA_SIP_DEREGISTRATION_REASON       = 383
DIA_SIP_REASON_CODE                 = 384
DIA_SIP_REASON_INFO                 = 385
DIA_SIP_VISITED_NETWORK_ID          = 386
DIA_SIP_USER_AUTHORIZATION_TYPE     = 387
DIA_SIP_SUPPORTED_USER_DATA_TYPE    = 388
DIA_SIP_USER_DATA                   = 389
DIA_SIP_USER_DATA_TYPE              = 390
DIA_SIP_USER_DATA_CONTENTS          = 391
DIA_SIP_USER_DATA_ALREADY_AVAILABLE = 392
DIA_SIP_METHOD                      = 393

#result codes (enum for result-code AVP)

DIAMETER_FIRST_REGISTRATION                  = 2003
DIAMETER_SUBSEQUENT_REGISTRATION             = 2004
DIAMETER_UNREGISTERED_SERVICE                = 2005
DIAMETER_SUCCESS_SERVER_NAME_NOT_STORED      = 2006
DIAMETER_SERVER_SELECTION                    = 2007
DIAMETER_SUCCESS_AUTH_SENT_SERVER_NOT_STORED = 2008
DIAMETER_USER_NAME_REQUIRED                  = 4013
DIAMETER_ERROR_USER_UNKNOWN                  = 5032
DIAMETER_ERROR_IDENTITIES_DONT_MATCH         = 5033
DIAMETER_ERROR_IDENTITY_NOT_REGISTERED       = 5034
DIAMETER_ERROR_ROAMING_NOT_ALLOWED           = 5035
DIAMETER_ERROR_IDENTITY_ALREADY_REGISTERED   = 5036
DIAMETER_ERROR_AUTH_SCHEME_NOT_SUPPORTED     = 5037
DIAMETER_ERROR_IN_ASSIGNMENT_TYPE            = 5038
DIAMETER_ERROR_TOO_MUCH_DATA                 = 5039
DIAMETER_ERROR_NOT_SUPPORTED_USER_DATA       = 5040

# AVPs inherited from RADIUS Extension for Digest Authentication (RFC4590)

DI_MESSAGE_AUTHENTICATOR    = 80
DI_DIGEST_RESPONSE          = 103
DI_DIGEST_REALM             = 104
DI_DIGEST_NONCE             = 105
DI_DIGEST_RESPONSE_AUTH     = 106
DI_DIGEST_NEXTNONCE         = 107
DI_DIGEST_METHOD            = 108 
DI_DIGEST_URI               = 109
DI_DIGEST_QOP               = 110 
DI_DIGEST_ALGORITM          = 111
DI_DIGEST_ENTITY_BODY_HASH  = 112
DI_DIGEST_CNONCE            = 113
DI_DIGEST_NONCE_COUNT       = 114
DI_DIGEST_USERNAME          = 115
DI_DIGEST_OPAQUE            = 116
DI_DIGEST_AUTH_PARAMS       = 117
DI_DIGEST_AKA_AUTS          = 118
DI_DIGEST_DOMAIN            = 119
DI_DIGEST_STALE             = 120
DI_DIGEST_HA1               = 121
DI_SIP_AOR                  = 122
